services:
  web:
    build:
      context: ./atom_project 
    ports:
      - "8000:8000"
    volumes:
      - ./atom_project:/usr/src/app
    env_file:
      - .env
    command: >
      sh -c "python create_test_data.py && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
