"""Nullable can_write

Revision ID: 9a23b2ff4e03
Revises: 908baaf1881b
Create Date: 2024-11-02 16:44:32.823960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a23b2ff4e03'
down_revision: Union[str, None] = '908baaf1881b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'can_write',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'can_write',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
